### ISSUE TITLE
容易误解的README内容

### ISSUE THREAD

**Issue by StoneMoe** [Loyalsoldier/surge-rules#12]
1. 规则项目间行为不一致
`direct.txt` 中包含了来自 [felixonmars/dnsmasq-china-list](https://github.com/felixonmars/dnsmasq-china-list) 的 google.china.conf 文件  
其内容为Google在中国“具有接入点”的域名列表  
但在您[Loyalsoldier/v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat) 项目中，`geosite:cn`中不包括该文件内容
2. `google.txt` 被描述为 谷歌域名列表
但该文件与`google.china.conf`文件内容完全一致  
应被描述为谷歌在中国具有接入点的域名列表，并考虑更名为`google-cn.txt`
3. `google.china.conf` 究竟应不应该包含在 direct.txt/geosite:cn 中
该列表并不能保证在中国的所有地区、所有时间内始终可用，不确定因素较大  
我个人更加偏向不包括在内  
或者考虑额外进行说明，否则容易导致在配置过程中花费更多时间来发现这个问题

**Comment by Loyalsoldier** [comment]
1. `geosite:cn` 中包含 `google.china.conf` 的域名。
2. 已修改描述。由于历史原因，文件就不改名了。
3. 有人希望包含，有人不希望包含，无法满足所有人。建议自行设置为代理。
