### ISSUE TITLE
使用surge-rules白名单domainset模式时，还需要配合使用maxmind库吗

### ISSUE THREAD

**Issue by lxp0gb** [Loyalsoldier/surge-rules#19]
你好，谢谢分享surge的Domainset。我有个疑问，贵站有geoip的maxmind库

如果我已经使用贵项目的surge domain set的白名单模式，还需加上配置maxmind库吗
geoip-maxmind-url = https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb

**Comment by Loyalsoldier** [comment]
如果自行配置了默认的 MaxMind geoip 库以外的 GEOIP 规则，如我提供的 geoip 的 `GEOIP,cloudflare` 等，就需要添加我生成的 geoip 库。
