### ISSUE TITLE
请问 让geosite:google全部走代理 该怎么配置

### ISSUE THREAD

**Issue by GeorgeRudd** [Loyalsoldier/surge-rules#20]
https://github.com/v2fly/domain-list-community/tree/master/data 中的geosite:google 怎么配置才能全部走proxy呢 本项目中是不是没有现成的规则

**Comment by Loyalsoldier** [comment]
将 google.txt 的 DIRECT 改为 PROXY

**Comment by Cavolo** [comment]
google.txt 目前看来已无意义。
[The Great Firewall of China has blocked google.com and all its subdomains](https://github.com/net4people/bbs/issues/128#issuecomment-1264339638)
