### ISSUE TITLE
请教一下， proxy.txt 和 gfw.txt 和 greatfire.txt  具体有什么区别？

### ISSUE THREAD

**Issue by discusssth** [Loyalsoldier/surge-rules#21]
这3个具体有什么区别呢？
 （根据我的理解， gfw就是最传统的被墙掉的网站列表， 那别的两个呢？）

![image](https://user-images.githubusercontent.com/45059308/197322298-bb4255e3-679d-4ba4-a6de-c35fb020dfdc.png)

**Comment by Loyalsoldier** [comment]
有重复项，可同时使用。列表说明见：https://github.com/Loyalsoldier/v2ray-rules-dat#geositedat

**Comment by isbasex** [comment]
没看懂 proxy.txt 收录域名的标准是什么，举个例子，我发现 apple.com 也在 proxy.txt 里面，但是这个域名在国内是可以直连的

**Comment by isbasex** [comment]
> 

@Loyalsoldier 可否帮忙详细解答下💁
