### ISSUE TITLE
请问本规则接受内容推荐吗？

### ISSUE THREAD

**Issue by PFbHzsiF** [Loyalsoldier/surge-rules#3]
我把reject.txt里的内容和我手里的广告过滤规则取了个交集，发现居然一条交集都没有。我想把我的规则贡献给你，然后改用你的这个domain-set方案可以吗？

**Comment by Loyalsoldier** [comment]
首先，如果是开源项目，需要看 LICENSE 是否兼容。其次，需要证明或验证规则的质量。欢迎到 https://github.com/Loyalsoldier/v2ray-rules-dat 提交 PR，该项目是本项目的父项目。

**Comment by PFbHzsiF** [comment]
https://github.com/vokins/yhosts

是这个已经被放弃的项目，上面完全没写关于license方面的情况。这个项目曾经还算是有名的，质量我猜挺好的吧。😂

**Comment by Loyalsoldier** [comment]
`This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.`

LICENSE 不兼容。
