### ISSUE TITLE
希望新增Dropbox相关的域名和IP规则集

### ISSUE THREAD

**Issue by TingTing1990** [Loyalsoldier/surge-rules#38]
为防止风控，希望Dropbox分流走固定的一个节点，希望新增Dropbox相关规则集，谢谢！

PS：Clash同

**Comment by Loyalsoldier** [comment]
等待项目重构吧。或者尝试自行添加规则，Dropbox 域名参考：https://github.com/v2fly/domain-list-community/blob/master/data/dropbox
