### ISSUE TITLE
使用DOMAIN-SET时，似乎不能命中规则，改为RULE-SET后命中

### ISSUE THREAD

**Issue by hsingll** [Loyalsoldier/surge-rules#39]
如题
先使用DOMAIN-SET：
<img width="1219" alt="Snipaste_2023-08-19_20-23-11" src="https://github.com/Loyalsoldier/surge-rules/assets/26346635/1edc4dbc-a6ff-439d-a1d1-9ff9eacc76fb">
改为RULE-SET后：
<img width="1219" alt="Snipaste_2023-08-19_20-22-10" src="https://github.com/Loyalsoldier/surge-rules/assets/26346635/1885c271-8928-402e-89df-4dbc2f3d9cc4">

**Comment by Loyalsoldier** [comment]
没有使用 Surge，不好复现。看 Surge 官网说明，DOMAIN-SET 规则确实是这样写的。

**Comment by hsingll** [comment]
> 没有使用 Surge，不好复现。看 Surge 官网说明，DOMAIN-SET 规则确实是这样写的。

没有问题，这行的规则地址不小心复制成Rule-set的了。不好意思。

**Comment by kid-oh** [comment]
> 好像是有这么个问题，DOMAIN-SET里的.cn似乎匹配不到，rule-set的话则正常

找到原因了：
The DOMAIN-SET rule doesn't support including an eTLD suffix due to performance optimization.

For example: .github.io won't match example.github.io

Here is the full eTLD list: https://publicsuffix.org/list/

Please use RULE-SET instead if you want to use eTLD as a suffix.
