### ISSUE TITLE
规则配置 PROXY 不太理解

### ISSUE THREAD

**Issue by toplyb** [Loyalsoldier/surge-rules#41]
在文档中，白名单下注意的第二条，原文是 `如你直接使用下面的 [Rule] 规则，则需要在 [Proxy] 或 [Proxy Group] 中手动配置一个名为 PROXY 的 policy`，这句不太理解，配置一个名为 `PROXY` 的话，那他对应的值应该写什么呢？麻烦指点一下，谢谢🙏

**Comment by Loyalsoldier** [comment]
配置文件参考：https://github.com/scomper/Surge/blob/1d69e8071122a885c98900e0c43512fdab27b6c4/surgeNew.conf#L29-L46

官方文档参考：
https://manual.nssurge.com/policy/proxy.html
https://manual.nssurge.com/policy/parameters.html
https://manual.nssurge.com/policy/group.html
