### ISSUE TITLE
无法添加外部规则集

### ISSUE THREAD

**Issue by hadwinfu** [Loyalsoldier/surge-rules#44]
surge for mac 5.5.0
全局代理+系统代理
已知代理可用

无法添加raw.githubusercontent.com上的，只能成功添加jsdelivr上的。
且无法解析DOMAIN-SET，只能解析RULE-SET。

**Comment by Loyalsoldier** [comment]
> 无法添加raw.githubusercontent.com上的，只能成功添加jsdelivr上的

DNS 污染问题

> 无法解析DOMAIN-SET，只能解析RULE-SET

那就用 RULE-SET
