### ISSUE TITLE
logs.netflix.com 在 reject.txt中

### ISSUE THREAD

**Issue by hadwinfu** [Loyalsoldier/surge-rules#45]
这个域名是收集信息用来识别代理防解锁的吗？

它存在于广告域名列表 reject.txt中，我设置了reject。但是在切换剧集的时候网页会不断发出（重试）有关这个域名的请求，貌似到达一定次数后才会加载切换的剧集。整个过程非常漫长。

**Comment by Loyalsoldier** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/165737
