### ISSUE TITLE
Telegram CIDR 有更新

### ISSUE THREAD

**Issue by hyfink** [Loyalsoldier/surge-rules#46]
不知道你用的什么源，一直打不开群组里的评论页面。
我网上搜了下tg官方提供的cidr源：
https://core.telegram.org/resources/cidr.txt
比你的多点。可以考虑换下。
最后谢谢提供这个工具！

**Comment by Loyalsoldier** [comment]
已囊括。官方的 CIDR 没有合并，看着数量多。Telegram 不止使用 IP，还使用域名
