### ISSUE TITLE
[tvos] remote resource is too large

### ISSUE THREAD

**Issue by hackenfu** [Loyalsoldier/surge-rules#47]
tvos版surge使用loyalsoldier的规则时，更新外部资源提示reject.txt太大，但是iOS版无此问题。是tvos本身的限制吗？有没有什么办法解决？
Remote resource is too large, please use themain app to update: https://cdn.jsdelivr.net/
gh/Loyalsoldier/surge-rules@release/reject.txt
(1.3 MB)

**Comment by Loyalsoldier** [comment]
没有使用 Surge，没有条件复现。看这个错误提示，似乎在暗示可以在 iOS Surge 中控制 tvOS 版 Surge？
