### ISSUE TITLE
bug: invalid line in cncidr domainset

### ISSUE THREAD

**Issue by lollipopkit** [Loyalsoldier/surge-rules#48]
![image](https://github.com/Loyalsoldier/surge-rules/assets/10864310/fb718286-61ac-4ea3-846a-d805c7c1cf22)

The exact line is: `IP-CIDR, 1.0.1.0/24`

Surge version: 5.11.1

Thanks.

**Comment by Loyalsoldier** [comment]
CIDR 类型的规则只能是 RULE-SET，不支持 DOMAIN-SET

**Comment by Loyalsoldier** [comment]
把 README 看完

**Comment by lollipopkit** [comment]
抱歉，我的问题
