### ISSUE TITLE
有点问题哈

### ISSUE THREAD

**Issue by lee19890212** [Loyalsoldier/surge-rules#5]
accelerated-domains.china.conf里面是
00.net
000060000.xyz
00042.com
0006266.com
0007.net
0008887.com
001133.app
该项目 direct里面是 
0.net
60000.xyz
42.com
6266.com
7.net
8887.com
1133.app
该项目尾部一串
regexp
regexp
regexp
regexp
regexp
regexp
regexp
regexp
regexp
regexp
该项目direct里面包含了部分apple跟google
下面有单独列出了 apple跟google的
直接转accelerated-domains.china.conf不就好了？

**Comment by Loyalsoldier** [comment]
`direct.txt` 和 `proxy.txt` 文件尾部的 regexp 是 bug，已修复。

由于本项目的所有列表都是自动收集的域名，不同列表之间难免有重复。所以需要配合说明文档使用，按照说明文档按照先后顺序放置规则才是最准确的。
