### ISSUE TITLE
配置规则后，surge 闪退

### ISSUE THREAD

**Issue by TryA9ain** [Loyalsoldier/surge-rules#52]
## surge 版本信息

Version 5.4.4 (2558)

![CleanShot 2024-09-23 at 17 35 24@2x](https://github.com/user-attachments/assets/c32a8efb-e0ee-4a3b-82c9-6084f3c77df7)

## 排查问题

经排查，问题出在以下两条规则，更新到这两个规则其中的任和一条规则就会闪退。

```
RULE-SET：
RULE-SET,https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/ruleset/proxy.txt,PROXY,force-remote-dns

DOMAIN-SET：
DOMAIN-SET,https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/proxy.txt,PROXY,force-remote-dns
```

> 2024.09.20 以前，上述这两条策略都可以正常使用，但 2024.09.23 早上突然 surge 开始闪退，尝试了：卸载了 helper 重装，卸载了 surge 重装，更换了 surge 不同的版本使用，这三种方法无论哪种，最终都会闪退。

## 免挨骂声明

不确定是否为我个人的特例情况，如果是特例，给作者大大造成打扰，请忽略，报拳了！

**Comment by NIL-zhuang** [comment]
surge 5.5.0 可以复现

**Comment by bingo619** [comment]
同样的问题，求解答

**Comment by 0x0021** [comment]
规则里去掉这个域名应该就好了
```enterprise.ac.uk```

**Comment by zhaodezhen** [comment]
> 规则里去掉这个域名应该就好了 `enterprise.ac.uk`

用浏览器打开这个网站 surge也会崩溃
