### ISSUE TITLE
国内域名解析到国外 ip

### ISSUE THREAD

**Issue by zscorpio** [Loyalsoldier/surge-rules#54]
<img width="1034" alt="image" src="https://github.com/user-attachments/assets/04287c1d-8334-47a5-a257-4ad7ec13a1c9" />
你好, 想咨询下国内域名解析到了非大陆ip, 有时候会解析到日本, 新加坡之类. 这有什么可能么, 不知道是不是哪里配置问题
47.246.38.140:443 (g.alicdn.com)

**Comment by zscorpio** [comment]
<img width="208" alt="image" src="https://github.com/user-attachments/assets/58748234-7952-4ee6-b26c-30aba05079b4" />
<img width="755" alt="image" src="https://github.com/user-attachments/assets/3a4306b7-4775-452f-9e1e-f083cb4276b6" />
你好, 想咨询下, 是需要把国外的 dns 全去掉么

**Comment by Loyalsoldier** [comment]
既然已经将国内常见域名都放在 cn 列表里的，可以去掉国外 DNS

**Comment by zscorpio** [comment]
感谢指导!

**Comment by Loyalsoldier** [comment]
既然国外常见域名、国内常见域名已经分别放在 proxy 列表和 direct 列表里了，可以删除国外 DNS。
