### ISSUE TITLE
关于解决cdn.jsdelivr.net更新延迟的问题

### ISSUE THREAD

**Issue by mangoclover** [Loyalsoldier/surge-rules#6]
关于解决`使用第二个地址（cdn.jsdelivr.net），但是内容更新会有 12 小时的延迟`的问题，您可以在 `.github/workflows/run.yml `最后加上下面的代码以清除缓存：

```
- name: Purge CDN Cache  
   run: |  
       curl -L https://purge.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/direct.txt > /dev/null 2>&1  
```
这样每次action运行完生成txt文件后都会清除cdn.jsdelivr.net的缓存，保证最新性。（非专业程序员，忽略表述专业性）☺️

**Comment by Loyalsoldier** [comment]
感谢提醒
