### ISSUE TITLE
Surge for macOS DOMAIN-SET 设置匹配不到 .cn

### ISSUE THREAD

**Issue by TomatosX** [Loyalsoldier/surge-rules#8]
direct.txt 规则集中中有包含 .cn 的规则，但是访问 .cn 网址时，走的是 FINAL。

<img width="257" alt="image" src="https://user-images.githubusercontent.com/5687392/126423184-9ae88ef0-4c85-46e4-ab86-0c54cb358664.png">

我的规则设置如下

```
[Rule]
PROCESS-NAME,Telegram,PROXY
PROCESS-NAME,Developer,PROXY
PROCESS-NAME,Twitter,PROXY
RULE-SET,LAN,DIRECT
RULE-SET,SYSTEM,DIRECT
DOMAIN-SET,https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/direct.txt,DIRECT
DOMAIN-SET,https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/private.txt,DIRECT
DOMAIN-SET,https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/proxy.txt,PROXY
DOMAIN-SET,https://cdn.jsdelivr.net/gh/Loyalsoldier/surge-rules@release/reject.txt,REJECT
FINAL,PROXY,dns-failed
```

匹配结果如下

<img width="503" alt="image" src="https://user-images.githubusercontent.com/5687392/126423447-4680827d-c43a-41a4-b836-ef06b8898481.png">

**Comment by Loyalsoldier** [comment]
没有购买 Surge，无法确认问题

**Comment by TomatosX** [comment]
更改规则解决了

**Comment by love4taylor** [comment]
> The DOMAIN-SET rule doesn't support include an eTLD suffix.

看起来是 Surge 的设计问题

https://community.nssurge.com/d/877-bug-report-improper-rule-priority-handling-of-domain-keyword/2

**Comment by asdfj2381k** [comment]
改为 domain-suffix,.cn,direct 应该可以解决
